services:
  - type: web
    name: uwi-msbm-gender-chatbot-monorepo-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: redirect
        source: /
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
    envVars:
      - key: NODE_VERSION
        value: 18.17.0